language: generic
services:
  - docker
before_install:
  - docker pull skylerlee/vim-testbed
jobs:
  include:
    - env: VIM=vim8
    - env: VIM=vim-latest
script:
  - |
    docker run -it --rm -v $PWD:/testplugin --entrypoint "/bin/bash" skylerlee/vim-testbed \
    scripts/bootstrap.sh
