language: generic
services:
  - docker
before_install:
  - docker pull skylerlee/vim-testbed
jobs:
  include:
    - env: VIMPATH=/vim-build/bin/vim8
    - env: VIMPATH=/vim-build/bin/vim-latest
script:
  - |
    docker run -it --rm -e VIMPATH=$VIMPATH --entrypoint "/bin/bash" \
    skylerlee/vim-testbed -c "echo started"
